apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: beershop
  creationTimestamp: null
  labels:
    pvc: mongo-data
  name: mongo-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
