apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    beershop.service: stock-service
  name: stock-service
  namespace: beershop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stock-service
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: ;http://+
        - name: JWT_AUDIENCE
          value: external-client
        - name: JWT_AUTHORITY
          value: http://k8s.keycloak.org/auth/realms/beershop
        - name: MONGODB_URL
          value: mongodb:27017
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: MONGODB_PASS
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password  
        image: sebchevre/stock-service:latest
        name: stock-service
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      initContainers:
      - name: rabbitmq
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup rabbitmq; do echo waiting for rabbitmq; sleep 2; done;']
status: {}
